- name:  Download client configs to the run directory folder on your local host
  fetch:
    src: "~/wg_clients/client_1/wg0-client.conf"
    dest: "{{ run_dir }}/{{ namespace }}.conf"
    flat: yes
  tags: "wg_fetch"
