- name: Disable timers for unattended upgrade, so that none will be triggered by the `date -s` call.
  raw: systemctl disable --now {{item}}
  with_items:
    - 'apt-daily.timer'
    - 'apt-daily-upgrade.timer'

- name: Reload systemctl daemon to apply the new changes
  raw: systemctl daemon-reload

- name: Wait for any possibly running unattended upgrade to finish
  raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true

- name: Purge unattended upgrades
  raw: apt-get -y purge unattended-upgrades    
  register: purge_uu
  until: purge_uu is not failed
  retries: 10

- name: Add the WireGuard PPA
  apt_repository:
    repo: 'ppa:wireguard/wireguard'

# Using with_items loop for apt module is deprecated
- name: Install WireGuard and other requirements
  apt:
    name:
      - linux-image-generic-hwe-18.04
      - linux-headers-generic-hwe-18.04
      - wireguard-dkms
      - wireguard-tools
      - python2.7
    state: present
    update_cache: true
  register: install_wg
  until: install_wg is not failed
  retries: 10

- name: Reboot the server
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true
  
- name: Wait for the reboot to complete if there was a change.
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
